--Provides User Raphael in schema RCABANGBANG permission to alter the tables
GRANT UPDATE,INSERT,DELETE,SELECT ON STUDENT TO RAPHAEL;
GRANT UPDATE,INSERT,DELETE,SELECT ON COURSE TO RAPHAEL;
GRANT UPDATE,INSERT,DELETE,SELECT ON ENROLL TO RAPHAEL;
GRANT UPDATE,INSERT,DELETE,SELECT ON TEACHER TO RAPHAEL;
GRANT UPDATE,INSERT,DELETE,SELECT ON SUBJECT TO RAPHAEL;