--changes to the tables from a different schema
--use after Grant.sql
DELETE FROM ENROLL WHERE COURSE_ID = 'C200';
UPDATE STUDENT SET FIRST_NAME = 'JERRY' WHERE STUDENT_ID = 1;
INSERT INTO STUDENT(STUDENT_ID, FIRST_NAME, LAST_NAME) VALUES (9, 'JIMMY', 'KING');
    

COMMIT;

SELECT * FROM ENROLL;
SELECT * FROM STUDENT;